# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/user/Documents/FPGA/mii_vhdl_example/vhdl_mii.cache/wt [current_project]
set_property parent.project_path /home/user/Documents/FPGA/mii_vhdl_example/vhdl_mii.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/user/Documents/FPGA/mii_vhdl_example/vhdl_mii.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/user/Documents/FPGA/mii_vhdl_example/vhdl_mii.srcs/sources_1/imports/mii_vhdl_example/eth_pkg.vhd
  /home/user/Documents/FPGA/mii_vhdl_example/sub_sync.vhd
  /home/user/Documents/FPGA/mii_vhdl_example/receiver.vhd
  /home/user/Documents/FPGA/mii_vhdl_example/transmitter.vhd
  /home/user/Documents/FPGA/mii_vhdl_example/sync.vhd
  /home/user/Documents/FPGA/mii_vhdl_example/vhdl_mii.srcs/sources_1/imports/mii_vhdl_example/ethernet.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ethernet -part xc7z020clg484-1


write_checkpoint -force -noxdef ethernet.dcp

catch { report_utilization -file ethernet_utilization_synth.rpt -pb ethernet_utilization_synth.pb }
